mysql:
  host: "localhost"
  port: 3306
  user: root
  database: RubyIsland
  password: "TAmebJRzA#1Rb"


general:
  prefix: "&e&lISOLOTTO&8: &f"
  world-name: "Isola"
  world-y: 6
  schematic-name: "Test"
  island-size: 30
  npc-name: "Luca"

points-system:
  # Lista di tutti i tipi di punti validi nel server.
  # Usa nomi semplici e in maiuscolo per coerenza.
  # Questi nomi verranno usati come 'key' nel database e nei comandi.
  types:
    - "ECONOMY"
    - "UCCISIONI"
    - "MINING"
    - "FARMING"
    - "EVENT_POINTS"


#PIANTE
plants:
  max-per-player: 4

#QUEST
quest-system:
  # L'ordine in cui le quest devono essere sbloccate.
  # I nomi devono corrispondere ai nomi dei file nella cartella /quests (senza .yml)
  order:
    - "1_scava_pietra"
    - "2_taglia_legna"

messages:
  plants:
    max-reached: "Hai raggiunto il massimo di piante nell'isola!"
    harvested: "Hai raccolto una pianta"
  teleport-own-island: "Sei andato sulla tua isola"
  teleport-other-island: "Sei andato sull'isola di %player%"
  wrong-argument: "Comando non corretto"
  island-not-found: "Questo giocatore non ha un'isola"
  you-not-have-island: "Non hai un isola, creala con il comando /is"
  player-not-found: "Questo giocatore non esiste"
  not-in-your-island: "Non sei sulla tua isola!"
  new-spawnpoint: "Nuovo punto di spawn impostato!"
  ban-player: "Hai bannato &c%player%&f dalla tua isola!"
  unban-player: "Hai sbannato &c%player%&f dalla tua isola!"
  add-player: "Adesso &c%player% &fpuò costruire quando tu sei online!"
  trust-player: "Adesso &c%player% &fpuò costruire sempre!"
  already-exist: "Questo giocatore è già %type%"
  banned: "Non puoi entrare in questa isola!"
  open: "Hai chiuso la tua isola, adesso nessuno (esclusi i giocatori a cui hai dato il permesso di costruire) potrà visitare la tua isola"
  close:  "Hai riaperto la tua isola!"
  already-in-status: "La tua isola è già %status%"
