mysql:
  host: "localhost"
  port: 3306
  user: root
  database: RubyIsland
  password: "TAmebJRzA#1Rb"


general:
  prefix: "&e&lISOLOTTO&8: &f"
  world-name: "Isola"
  schematic-name: "Test"
  island-size: 30


messages:
  teleport-own-island: "Sei andato sulla tua isola"
  teleport-other-island: "Sei andato sull'isola di %player%"
  wrong-argument: "Comando non corretto"
  island-not-found: "Questo giocatore non ha un'isola"
  you-not-have-island: "Non hai un isola, creala con il comando /is"
  player-not-found: "Questo giocatore non esiste"
  not-in-your-island: "Non sei sulla tua isola!"
  new-spawnpoint: "Nuovo punto di spawn impostato!"
  ban-player: "Hai bannato &c%player%&f dalla tua isola!"
  unban-player: "Hai sbannato &c%player%&f dalla tua isola!"
  add-player: "Adesso &c%player% &fpuò costruire quando tu sei online!"
  trust-player: "Adesso &c%player% &fpuò costruire sempre!"
  already-exist: "Questo giocatore è già %type%"
  banned: "Non puoi entrare in questa isola!"